#!/bin/bash
# This is a simple post deploy hook executed after your application
# is deployed and started.  This script gets executed directly, so
# it could be python, php, ruby, etc.

#  Do spy on deploy
node ${OPENSHIFT_REPO_DIR}/index.js
